// Generated by scripts/build-wasm-verifiers.mjs from tools/nvidia-verifier/source-lock.json.
export const NVIDIA_ARTIFACTS = Object.freeze({
  "nvattest.wasm": "c4bbe723569ee84c0a03d43664c7d7b4c091eca4bbcf5acfa86008ebbb29ef2f",
  "nvattest.mjs": "2e17aded359c413300d6c8de0da1caa2ea2f59f96bfd4d9bd593d78cec666722"
});
