// Generated by scripts/build-wasm-verifiers.mjs from tools/nvidia-verifier/source-lock.json.
export const WASM_ARTIFACTS = Object.freeze({
  "tinfoil-public-build.wasm": "2a106eb1a399f9b85e8fff54041a4c336f206e29a76dc212db49909ba81026c9"
});
