// Generated by scripts/build-wasm-verifiers.mjs from tools/nvidia-verifier/source-lock.json.
export const WASM_ARTIFACTS = Object.freeze({
  "nvattest.wasm.gz": "9199625668bc30b6b8f026d5b45925a27a48f9db7c0f31cdccab6f4e4a15f177",
  "nvattest.mjs": "2e17aded359c413300d6c8de0da1caa2ea2f59f96bfd4d9bd593d78cec666722",
  "tinfoil-public-build.wasm.gz": "6a6de9d31594221f8b3ad05b6b24898ed21c3350815ce165e05c7a8533acb6a7"
});
